=== 0xZee/mongodb_rag/IT_value_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "_id": {
        "type": "integer"
      },
      "Mon_role": {
        "type": "string"
      },
      "time_slot": {
        "type": "string"
      },
      "Creneau MEP": {
        "type": "string",
        "pattern": "^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2} \\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$"
      },
      "Ref_MEP": {
        "type": "string",
        "pattern": "^MEP_\\d+$"
      },
      "Statut_MEP": {
        "type": "string"
      },
      "operation_notice_date": {
        "type": "string",
        "format": "date"
      },
      "operation_end_report_date": {
        "type": "string",
        "format": "date"
      },
      "post_operation_report_date": {
        "type": "string"
      },
      "application": {
        "type": "string"
      },
      "operation_title": {
        "type": "string"
      },
      "service_impact": {
        "type": "string"
      },
      "Preparateur MEP": {
        "type": "string",
        "pattern": "^user_\\d+$"
      },
      "operation_owner": {
        "type": "string",
        "pattern": "^user_\\d+$"
      },
      "Ref_Projet": {
        "type": "string"
      }
    },
    "required": [
      "_id",
      "Mon_role",
      "time_slot",
      "Creneau MEP",
      "Ref_MEP",
      "Statut_MEP",
      "operation_notice_date",
      "operation_end_report_date",
      "post_operation_report_date",
      "application",
      "operation_title",
      "service_impact",
      "Preparateur MEP",
      "operation_owner",
      "Ref_Projet"
    ]
  }
}

=== 0xZee/mongodb_rag/IT_value.json
[
  {
    "_id": 1,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "23/09/2024 22:00 24/09/2024 02:00",
    "Ref_MEP": "MEP_1234",
    "Statut_MEP": "OK",
    "operation_notice_date": "23/09/2024",
    "operation_end_report_date": "28/09/2024",
    "post_operation_report_date": "",
    "application": "App_Alpha",
    "operation_title": "[PROJET_A] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_001",
    "operation_owner": "user_023",
    "Ref_Projet": "[RESEAU][PROJET_A]"
  },
  {
    "_id": 2,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "24/09/2024 22:00 25/09/2024 02:00",
    "Ref_MEP": "MEP_1235",
    "Statut_MEP": "OK",
    "operation_notice_date": "24/09/2024",
    "operation_end_report_date": "29/09/2024",
    "post_operation_report_date": "",
    "application": "App_Beta",
    "operation_title": "[PROJET_B] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_002",
    "operation_owner": "user_024",
    "Ref_Projet": "[RESEAU][PROJET_B]"
  },
  {
    "_id": 3,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "25/09/2024 22:00 26/09/2024 02:00",
    "Ref_MEP": "MEP_1236",
    "Statut_MEP": "OK",
    "operation_notice_date": "25/09/2024",
    "operation_end_report_date": "30/09/2024",
    "post_operation_report_date": "",
    "application": "App_Gamma",
    "operation_title": "[PROJET_C] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_003",
    "operation_owner": "user_025",
    "Ref_Projet": "[RESEAU][PROJET_C]"
  },
  {
    "_id": 4,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "26/09/2024 22:00 27/09/2024 02:00",
    "Ref_MEP": "MEP_1237",
    "Statut_MEP": "OK",
    "operation_notice_date": "26/09/2024",
    "operation_end_report_date": "01/10/2024",
    "post_operation_report_date": "",
    "application": "App_Delta",
    "operation_title": "[PROJET_D] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_004",
    "operation_owner": "user_026",
    "Ref_Projet": "[RESEAU][PROJET_D]"
  },
  {
    "_id": 5,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "27/09/2024 22:00 28/09/2024 02:00",
    "Ref_MEP": "MEP_1238",
    "Statut_MEP": "OK",
    "operation_notice_date": "27/09/2024",
    "operation_end_report_date": "02/10/2024",
    "post_operation_report_date": "",
    "application": "App_Epsilon",
    "operation_title": "[PROJET_E] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_005",
    "operation_owner": "user_027",
    "Ref_Projet": "[RESEAU][PROJET_E]"
  },
  {
    "_id": 6,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "28/09/2024 22:00 29/09/2024 02:00",
    "Ref_MEP": "MEP_1239",
    "Statut_MEP": "OK",
    "operation_notice_date": "28/09/2024",
    "operation_end_report_date": "03/10/2024",
    "post_operation_report_date": "",
    "application": "App_Zeta",
    "operation_title": "[PROJET_F] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_006",
    "operation_owner": "user_028",
    "Ref_Projet": "[RESEAU][PROJET_F]"
  },
  {
    "_id": 7,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "29/09/2024 22:00 30/09/2024 02:00",
    "Ref_MEP": "MEP_1240",
    "Statut_MEP": "OK",
    "operation_notice_date": "29/09/2024",
    "operation_end_report_date": "04/10/2024",
    "post_operation_report_date": "",
    "application": "App_Eta",
    "operation_title": "[PROJET_G] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_007",
    "operation_owner": "user_029",
    "Ref_Projet": "[RESEAU][PROJET_G]"
  },
  {
    "_id": 8,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "30/09/2024 22:00 01/10/2024 02:00",
    "Ref_MEP": "MEP_1241",
    "Statut_MEP": "OK",
    "operation_notice_date": "30/09/2024",
    "operation_end_report_date": "05/10/2024",
    "post_operation_report_date": "",
    "application": "App_Theta",
    "operation_title": "[PROJET_H] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_008",
    "operation_owner": "user_030",
    "Ref_Projet": "[RESEAU][PROJET_H]"
  },
  {
    "_id": 9,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "01/10/2024 22:00 02/10/2024 02:00",
    "Ref_MEP": "MEP_1242",
    "Statut_MEP": "OK",
    "operation_notice_date": "01/10/2024",
    "operation_end_report_date": "06/10/2024",
    "post_operation_report_date": "",
    "application": "App_Iota",
    "operation_title": "[PROJET_I] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_009",
    "operation_owner": "user_031",
    "Ref_Projet": "[RESEAU][PROJET_I]"
  },
  {
    "_id": 10,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "02/10/2024 22:00 03/10/2024 02:00",
    "Ref_MEP": "MEP_1243",
    "Statut_MEP": "OK",
    "operation_notice_date": "02/10/2024",
    "operation_end_report_date": "07/10/2024",
    "post_operation_report_date": "",
    "application": "App_Kappa",
    "operation_title": "[PROJET_J] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_010",
    "operation_owner": "user_032",
    "Ref_Projet": "[RESEAU][PROJET_J]"
  },
  {
    "_id": 11,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "03/10/2024 22:00 04/10/2024 02:00",
    "Ref_MEP": "MEP_1244",
    "Statut_MEP": "OK",
    "operation_notice_date": "03/10/2024",
    "operation_end_report_date": "08/10/2024",
    "post_operation_report_date": "",
    "application": "App_Lambda",
    "operation_title": "[PROJET_K] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_011",
    "operation_owner": "user_033",
    "Ref_Projet": "[RESEAU][PROJET_K]"
  },
  {
    "_id": 12,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "04/10/2024 22:00 05/10/2024 02:00",
    "Ref_MEP": "MEP_1245",
    "Statut_MEP": "OK",
    "operation_notice_date": "04/10/2024",
    "operation_end_report_date": "09/10/2024",
    "post_operation_report_date": "",
    "application": "App_Mu",
    "operation_title": "[PROJET_L] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_012",
    "operation_owner": "user_034",
    "Ref_Projet": "[RESEAU][PROJET_L]"
  },
  {
    "_id": 13,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "05/10/2024 22:00 06/10/2024 02:00",
    "Ref_MEP": "MEP_1246",
    "Statut_MEP": "OK",
    "operation_notice_date": "05/10/2024",
    "operation_end_report_date": "10/10/2024",
    "post_operation_report_date": "",
    "application": "App_Nu",
    "operation_title": "[PROJET_M] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_013",
    "operation_owner": "user_035",
    "Ref_Projet": "[RESEAU][PROJET_M]"
  },
  {
    "_id": 14,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "06/10/2024 22:00 07/10/2024 02:00",
    "Ref_MEP": "MEP_1247",
    "Statut_MEP": "OK",
    "operation_notice_date": "06/10/2024",
    "operation_end_report_date": "11/10/2024",
    "post_operation_report_date": "",
    "application": "App_Xi",
    "operation_title": "[PROJET_N] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_014",
    "operation_owner": "user_036",
    "Ref_Projet": "[RESEAU][PROJET_N]"
  },
  {
    "_id": 15,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "07/10/2024 22:00 08/10/2024 02:00",
    "Ref_MEP": "MEP_1248",
    "Statut_MEP": "OK",
    "operation_notice_date": "07/10/2024",
    "operation_end_report_date": "12/10/2024",
    "post_operation_report_date": "",
    "application": "App_Omicron",
    "operation_title": "[PROJET_O] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_015",
    "operation_owner": "user_037",
    "Ref_Projet": "[RESEAU][PROJET_O]"
  },
  {
    "_id": 16,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "08/10/2024 22:00 09/10/2024 02:00",
    "Ref_MEP": "MEP_1249",
    "Statut_MEP": "OK",
    "operation_notice_date": "08/10/2024",
    "operation_end_report_date": "13/10/2024",
    "post_operation_report_date": "",
    "application": "App_Pi",
    "operation_title": "[PROJET_P] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_016",
    "operation_owner": "user_038",
    "Ref_Projet": "[RESEAU][PROJET_P]"
  },
  {
    "_id": 17,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "09/10/2024 22:00 10/10/2024 02:00",
    "Ref_MEP": "MEP_1250",
    "Statut_MEP": "OK",
    "operation_notice_date": "09/10/2024",
    "operation_end_report_date": "14/10/2024",
    "post_operation_report_date": "",
    "application": "App_Rho",
    "operation_title": "[PROJET_Q] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_017",
    "operation_owner": "user_039",
    "Ref_Projet": "[RESEAU][PROJET_Q]"
  },
  {
    "_id": 18,
    "Mon_role": "Gestionnaire de MEP",
    "time_slot": "HNO Soir",
    "Creneau MEP": "10/10/2024 22:00 11/10/2024 02:00",
    "Ref_MEP": "MEP_1251",
    "Statut_MEP": "OK",
    "operation_notice_date": "10/10/2024",
    "operation_end_report_date": "15/10/2024",
    "post_operation_report_date": "",
    "application": "App_Sigma",
    "operation_title": "[PROJET_R] Upgrade instance",
    "service_impact": "Aucun",
    "Preparateur MEP": "user_018",
    "operation_owner": "user_040",
    "Ref_Projet": "[RESEAU][PROJET_R]"
  },
  {
    "_id": 19,
    "Mon_role": "Gestionnaire de MEP",
